name: MedyaPress
options:
  bundleIdPrefix: press.medya
  deploymentTarget:
    iOS: "15.0"

targets:
  MedyaPress:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MedyaPress
      - WebView.swift
      - MedyaPressApp.swift
      - LaunchScreen.storyboard
    info:
      path: MedyaPress/Info.plist
